---

- src: https://github.com/superlumic/ansible-role-homebrew.git
  name: homebrew

- src: https://github.com/superlumic/ansible-role-osx-defaults.git
  name: osx-defaults

- src: https://github.com/superlumic/ansible-role-computername.git
  name: computername

- src: https://github.com/superlumic/ansible-role-cli.git
  name: cli

- src: https://github.com/superlumic/ansible-role-mysql.git
  name: mysql

- src: https://github.com/superlumic/ansible-role-php.git
  name: php

- src: https://github.com/superlumic/ansible-role-sublimetext.git
  name: sublimetext

- src: https://github.com/superlumic/ansible-role-node.git
  name: node

- src: https://github.com/superlumic/ansible-role-postgresql.git
  name: postgresql

- src: https://github.com/superlumic/ansible-role-vim.git
  name: vim

- src: https://github.com/superlumic/ansible-role-skylab.git
  name: skylab
